# Generated by Django 2.2 on 2020-01-23 19:31

from django.db import migrations, models
import glucoApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=glucoApp.models.get_obs_upload_path, verbose_name='Image')),
                ('value', models.CharField(blank=True, max_length=10, null=True, verbose_name='Value')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirm')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
